package com.fei.prepravnispolecnost.model;

// Generated 12.2.2013 8:11:18 by Hibernate Tools 3.2.1.GA



/**
 * Customer generated by hbm2java
 */
public class CustomerDTO implements java.io.Serializable{

    private Integer id;
    private AddressDTO address;
    private String login;
    private String password;
    private String passwordAgain;
    private String name;
    private String surname;
    private String email;
    private Integer tel;
    private String ico;
    private String dic;
    private String company;

    public CustomerDTO() {
    }

    public CustomerDTO(AddressDTO address, String login, String password, String name, String surname, String email, Integer tel, String ico, String dic, String company) {
        this.address = address;
        this.login = login;
        this.password = password;
        this.name = name;
        this.surname = surname;
        this.email = email;
        this.tel = tel;
        this.ico = ico;
        this.dic = dic;
        this.company = company;
    }

    public String getPasswordAgain() {
        return passwordAgain;
    }

    public void setPasswordAgain(String passwordAgain) {
        this.passwordAgain = passwordAgain;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public AddressDTO getAddress() {
        return this.address;
    }

    public void setAddress(AddressDTO address) {
        this.address = address;
    }

    public String getLogin() {
        return this.login;
    }

    public void setLogin(String login) {
        this.login = login;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getSurname() {
        return this.surname;
    }

    public void setSurname(String surname) {
        this.surname = surname;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public Integer getTel() {
        return this.tel;
    }

    public void setTel(Integer tel) {
        this.tel = tel;
    }

    public String getIco() {
        return this.ico;
    }

    public void setIco(String ico) {
        this.ico = ico;
    }

    public String getDic() {
        return this.dic;
    }

    public void setDic(String dic) {
        this.dic = dic;
    }

    public String getCompany() {
        return this.company;
    }

    public void setCompany(String company) {
        this.company = company;
    }
}
